from guizero import App, Combo, Text, CheckBox, ButtonGroup, PushButton, info

def search_network():
    sport_network = d_sports.get(sport.value, "not found")
    info("Sport Network", f"You can watch on {sport_network}")


app = App(title="Sport Network Finder", width=300, height=200, layout="grid")
sport = Combo(app, options=["Select One", "A-League - Sydney FC vs Adelaide United", "A-League - Central Coast Mariners vs Perth Glory", "A-League - Western Sydney Wanderers vs Newcastle Jets", "A-League - Brisbane Roar vs Melbourne Victory", "A-League - Central Coast Mariners vs Western United", "A-League - Macarthur FC vs Sydney FC", "A-League - Adelaide United vs Perth Glory", "A-League - Melbourne City vs Wellington Phoenix", "A-League - Melbourne Victory vs Newcastle Jets", "A-League - Melbourne City vs Perth Glory", "A-League - Western Sydney Wanderers vs Central Coast Mariners", "A-League - Wellington Phoenix vs Macarthur FC", "A-League - Brisbane Roar vs Sydney FC", "A-League - Western United vs Adelaide United", "A-League - Adelaide United vs Melbourne Victory", "A-League - Newcastle Jets vs Melbourne City", "A-League - Sydney FC vs Western Sydney Wanderers", "A-League - Wellington Phoenix vs Western United", "A-League - Central Coast Mariners vs Macarthur FC", "A-League - Brisbane Roar vs Adelaide United", "A-League - Wellington Phoenix vs Western Sydney Wanderers", "A-League - Perth Glory vs Western United", "A-League - Sydney FC vs Melbourne Victory", "A-League - Central Coast Mariners vs Newcastle Jets 1", "A-League - Macarthur FC vs Melbourne Victory", "A-League - Newcastle Jets vs Brisbane Roar", "A-League - Wellington Phoenix vs Adelaide United", "A-League - Central Coast Mariners vs Sydney FC", "A-League - Melbourne City vs Melbourne Victory", "A-League - Western United vs Western Sydney Wanderers", "A-League - Macarthur FC vs Perth Glory", "EPL - Brighton & Hove Alvion vs Nottingham Forest", "EPL - Crystal Palace vs Wolverhampton Wanderers", "EPL - Brentford vs Chelsea", "EPL - Newcastle vs Everton", "EPL - Liverpool vs West Ham", "EPL - Bournermouth vs Southampton", "EPL - Manchester United vs Tottenham", "EPL - Fulham vs Aston Villa", "EPL - Leicester City vs Leeds United", "EPL - Nottingham Forest vs Liverpool", "EPL - Everton vs Crystal Palace", "EPL - Manchester City vs Brighton & Hove Albion", "EPL - Chelsea vs Manchester United", "EPL - Wolverhampton Wanderers vs Leicester City", "EPL - Leeds United vs Fulham", "EPL - Southampton vs Arsenal", "EPL - Aston Villa vs Brentford", "EPL - Tottenham vs Newcastle", "EPL - West Ham vs Bournemouth", "NFL - Colts & Broncos", "NFL International Series - Giants & Packers", "NFL - Falcons & Buccaneers", "NFL - Bears & Vikings", "NFL - Lions & Patriots", "NFL - Seahawks & Saints", "NFL - Steelers & Bills", "NFL - Chargers & Browns", "NFL - Texans & Jaguars", "NFL - Dolphins & Jets", "NFL - Titans & Commanders", "NFL - 49ers & Panthers", "NFL - Cowboys & Rams", "NFL - Eagles & Cardinals", "NFL - Bengals & Ravens", "NFL - Raiders & Chiefs", "NFL - Commanders & Bears", "NFL - Bengals & Saints", "NFL - Ravens & Giants", "NFL - Patriots & Browns", "NFL - Jaguars & Colts", "NFL - Buaccaneers & Steelers", "NFL - Vikings & Dolphins", "NFL - 48ers & Falcons", "NFL - Jets & Packers", "NFL - Panthers & Rams", "NFL - Cardinals & Seahawks", "NFL - Bills & Chiefs", "NFL - Cowboys & Eagles", "NFL - Broncos & Chargers", "NFL - Buccaneers & Panthers", "NFL - Falcons & Bengals", "NFL - Giants & Jaguars", "NFL - Packers & Commanders", "NFL - Lions & Cowboys", "NFL - Browns & Ravens", "NFL - Colts & Titans", "NFL - Jets & Broncos", "NFL - Texans & Raiders", "NFL - Chiefs & 49ers", "NFL - Seahawks & Chargers", "NFL - Steelers & Dolphins", "NFL - Bears & Patriots", "NFL - Ravens & Buccaneers", "NFL International Series - Broncos & Jaguars", "NFL - Bears & Cowboys", "NFL - Panthers & Falcons", "NFL - Cardinals & Vikings", "NFL - Raiders & Saints", "NFL - Steelers & Eagles", "NFL - Dolphins & Lions", "NFL - Patriots & Jets", "NFL - Titans & Texans", "NFL - 49ers & Rams", "NFL - Giants & Seahawks", "NFL - Commanders & Colts", "NFL - Packers & Bills", "NFL - Bengals & Browns", "NFL - Eagles & Texans", "NFL - Colts & Patriots", "NFL - Raiders & Jaguars", "NFL - Dolphins & Bears", "NFL - Bills & Jets", "NFL - Packers & Lions", "NFL - Chargers & Falcons", "NFL - Panthers & Bengals", "NFL - Vikings & Commanders", "NFl - Seahawks & Cardinals", "NFL - Rams & Buccaneers", "NFL - Titans & Chiefs", "NFL - Ravens & Saints", "NFL - Falcons & Panthers", "NFL International Series - Seahawks & Buccaneers", "NFL - Saints & Steelers", "NFL - VIkings & Bills", "NFL - Lions & Bears", "NFL - Broncos & Titans", "NFL - Jaguars & Chiefs", "NFL - Browns & Dolphins", "NFL - Texans & Giants", "NFL - Colts & Raiders", "NFL - Cowboys & Packers", "NFL - Cardinals & Rams", "NFL - Chargers & 49ers", "NFL - Commanders & Eagles", "NFL - Titans & Packers", "NFL - Browns & Bills", "NFL - Eagles & Colts", "NFL - Jets & Patriots", "NFL - Rams & Saints", "NFL - Bears & Falcons", "NFL - Panthers & Ravens", "NFL - Commanders & Texans", "NFL - Lions & Giants", "NFL - Raiders & Broncos", "NFL - Chiefs & Chargers", "NFL - Cowboys & Vikings", "NFL - Bengals & Steelers", "NFL International Series - 49ers & Cardinals", "NFL Thanksgiving - Bills & Lions", "NFL Thanksgiving - Giants & Cowboys", "NFL Thanksgiving - Patriots & Vikings", "NFL - Buccaneers & Browns", "NFL - Broncos & Panthers", "NFL - Falcons & Commanders", "NFL - Bears & Jets", "NFL - Bengals & Titans", "NFL - Ravens & Jaguars", "NFL - Texans & Dolphins", "NFL - Chargers & Cardinals", "NFL - Raiders & Seahawks", "NFL - Rams & Chiefs", "NFL - Saints & 49ers", "NFL - Packers & Eagles", "NFL - Steelers & Colts", "NFL - Broncos & Ravens", "NFL - Browns & Texans", "NFL - Jets & Vikings", "NFL - Steelers & Falcons", "NFL - Packers & Bears", "NFL - Titans & Eagles", "NFL - Jaguars & Lions", "NFL - Commanders & Giants", "NFL - Seahawks & Rams", "NFL - Dolphins & 49ers", "NFL - Chiefs & Bengals", "NFL - Chiefs & Bengals", "NFL - Chargers & Raiders", "NFL - Colts & Cowboys", "NFL - Saints & Buccaneers", "NFL - Raiders & Rams", "NFL - Texans & Cowboys", "NFL - Eagles & Giants", "NFL - Vikings & Lions", "NFL - Browns & Bengals", "NFL - Ravens & Steelers", "NFL - Jets & Bills", "NFL - Jaguars & Titans", "NFL - Dolphins & Chargers", "NFL - Buccaneers & 49ers", "NFL - Panthers & Seahawks", "NFL - Chiefs & Broncos", "NFL - Patriots & Cardinals", "NFL - 49ers & Seahawks"], grid=[0,1], align="left")
button = PushButton(app, command=search_network, text="Search Network", grid=[0,2], align="left")

d_sports = {
    "NFL - Colts & Broncos": "Amazon Prime",
    "NFL International Series - Giants & Packers": "NFL Network",
    "NFL - Falcons & Buccaneers": "FOX",
    "NFL - Bears & Vikings": "FOX",
    "NFL - Lions & Patriots": "FOX",
    "NFL - Seahawks & Saints": "FOX",
    "NFL - Steelers & Bills": "CBS or Paramount+",
    "NFL - Chargers & Browns": "CBS or Paramount+",
    "NFL - Texans & Jaguars": "CBS or Paramount+",
    "NFL - Dolphins & Jets": "CBS or Paramount+",
    "NFL - Titans & Commanders": "CBS or Paramount+",
    "NFL - 49ers & Panthers": "Unknown",
    "NFL - Cowboys & Rams": "FOX",
    "NFL - Eagles & Cardinals": "FOX",
    "NFL - Bengals & Ravens": "NBC or Peacock",
    "NFL - Raiders & Chiefs": "ESPN",
    "NFL - Commanders & Bears": "Amazon Prime",
    "NFL - Bengals & Saints": "CBS or Paramount+",
    "NFL - Ravens & Giants": "CBS or Paramount+",
    "NFL - Patriots & Browns": "CBS or Paramount+",
    "NFL - Jaguars & Colts": "CBS or Paramount+",
    "NFL - Jets & Packers": "FOX",
    "NFL - Buccaneers & Steelers": "FOX",
    "NFL - 49ers & Falcons": "FOX",
    "NFL - Vikings & Dolphins": "FOX",
    "NFL - Panthers & Rams": "Unknown",
    "NFL - Cardinals & Seahawks": "Unknown",
    "NFL - Bills & Chiefs": "CBS or Paramount+",
    "NFL - Cowboys & Eagles": "NBC or Peacock",
    "NFL - Broncos & Chargers": "ESPN",
    "NFL - Saints & Cardinals": "Amazon Prime",
    "NFL - Buccaneers & Panthers": "FOX",
    "NFL - Falcons & Bengals": "FOX",
    "NFL - Giants & Jaguars": "FOX",
    "NFL - Packers & Commanders": "FOX",
    "NFL - Lions & Cowboys": "CBS or Paramount+",
    "NFL - Browns & Ravens": "CBS or Paramount+",
    "NFL - Colts & Titans": "CBS or Paramount+",
    "NFL - Jets & Broncos": "CBS or Paramount+",
    "NFL - Texans & Raiders": "CBS or Paramount+",
    "NFL - Chiefs & 49ers": "FOX",
    "NFL - Seahawks & Chargers": "FOX",
    "NFL - Steelers & Dolphins": "NBC or Peacock",
    "NFL - Bears & Patriots": "ESPN",
    "NFL - Ravens & Buccaneers": "Amazon Prime",
    "NFL International Series - Broncos & Jaguars": "ESPN+",
    "NFL - Bears & Cowboys": "FOX",
    "NFL - Panthers & Falcons": "FOX",
    "NFL - Cardinals & Vikings": "FOX",
    "NFL - Raiders & Saints": "CBS or Paramount+",
    "NFL - Steelers & Eagles": "CBS or Paramount+",
    "NFL - Dolphins & Lions": "CBS or Paramount+",
    "NFL - Patriots & Jets": "CBS or Paramount+",
    "NFL - Titans & Texans": "CBS or Paramount+",
    "NFL - 49ers & Rams": "FOX",
    "NFL - Giants & Seahawks": "FOX",
    "NFL - Commanders & Colts": "FOX",
    "NFL - Packers & Bills": "NBC or Peacock",
    "NFL - Bengals & Browns": "ESPN",
    "NFL - Eagles & Texans": "Amazon Prime",
    "NFL - Colts & Patriots": "CBS or Paramount+",
    "NFL - Raiders & Jaguars": "CBS or Paramount+",
    "NFL - Dolphins & Bears": "CBS or Paramount+",
    "NFL - Bills & Jets": "CBS or Paramount+",
    "NFL - Packers & Lions": "FOX",
    "NFL - Chargers & Falcons": "FOX",
    "NFL - Panthers & Bengals": "FOX",
    "NFL - Vikings & Commanders": "FOX",
    "NFL - Seahawks & Cardinals": "FOX",
    "NFL - Rams & Buccaneers": "CBS or Paramount+",
    "NFL - Titans & Chiefs": "NBC or Peacock",
    "NFL - Ravens & Saints": "ESPN",
    "NFL - Falcons & Panthers": "Amazon Prime",
    "NFL International Series - Seahawks & Buccaneers": "NFL Network",
    "NFL - Saints & Steelers": "FOX",
    "NFL - Vikings & Bills": "FOX",
    "NFL - Lions & Bears": "FOX",
    "NFL - Broncos & Titans": "CBS or Paramount+",
    "NFL - Jaguars & Chiefs": "CBS or Paramount+",
    "NFL - Browns & Dolphins": "CBS or Paramount+",
    "NFL - Texans & Giants": "CBS or Paramount+",
    "NFL - Colts & Raiders": "CBS or Paramount+",
    "NFL - Cowboys & Packers": "FOX",
    "NFL - Cardinals & Rams": "FOX",
    "NFL - Chargers & 49ers": "NBC or Peacock",
    "NFL - Commanders & Eagles": "ESPN",
    "NFL - Titans & Packers": "Amazon Prime",
    "NFL - Browns & Bills": "CBS or Paramount+",
    "NFL - Eagles & Colts": "CBS or Paramount+",
    "NFL - Jets & Patriots": "CBS or Paramount+",
    "NFL - Rams & Saints": "FOX",
    "NFL - Bears & Falcons": "FOX",
    "NFL - Panthers & Ravens": "FOX",
    "NFL - Commanders & Texans": "FOX",
    "NFL - Lions & Giants": "FOX",
    "NFL - Raiders & Broncos": "FOX",
    "NFL - Chiefs & Chargers": "CBS or Paramount+",
    "NFL - Cowboys & Vikings": "CBS or Paramount+",
    "NFL - Bengals & Steelers": "NBC or Peacock",
    "NFL International Series - 49ers & Cardinals": "ESPN",
    "NFL Thanksgiving - Bills & Lions": "CBS or Paramount+",
    "NFL Thanksgiving - Giants & Cowboys": "FOX",
    "NFL Thanksgiving - Patriots & Vikings": "NBC or Peacock",
    "NFL - Buccaneers & Browns": "FOX",
    "NFL - Broncos & Panthers": "FOX",
    "NFL = Falcons & Commanders": "FOX",
    "NFL - Bears & Jets": "FOX",
    "NFL - Bengals & Titans": "CBS or Paramount+",
    "NFL - Ravens & Jaguars": "CBS or Paramount+",
    "NFL - Texans & Dolphins": "CBS or Paramount+",
    "NFL - Chargers & Cardinals": "CBS or Paramount+",
    "NFL - Raiders & Seahawks": "CBS or Paramount+",
    "NFL - Rams & Chiefs": "FOX",
    "NFL - Saints & 49ers": "FOX",
    "NFL - Packers & Eagles": "NBC or Peacock",
    "NFL - Steelers & Colts": "ESPN",
    "NFL - Bills & Patriots": "Amazon Prime",
    "NFL - Broncos & Ravens": "CBS or Paramount+",
    "NFL - Browns & Texans": "CBS or Paramount+",
    "NFL - Jets & Vikings": "CBS or Paramount+",
    "NFL - Steelers & Falcons": "CBS or Paramount+",
    "NFL - Packers & Bears": "FOX",
    "NFL - Titans & Eagles": "FOX",
    "NFL - Jaguars & Lions": "FOX",
    "NFL - Commanders & Giants": "FOX",
    "NFL - Seahawks & Rams": "FOX",
    "NFL - Dolphins & 49ers": "FOX",
    "NFL - Chiefs & Bengals": "CBS or Paramount+",
    "NFL - Chargers & Raiders": "CBS or Paramount+",
    "NFL - Colts & Cowboys": "NBC or Peacock",
    "NFL - Saints & Buccaneers": "ESPN",
    "NFL - Raiders & Rams": "Amazon Prime",
    "NFL - Texans & Cowboys": "FOX",
    "NFL - Eagles & Giants": "FOX",
    "NFL - Vikings & Lions": "FOX",
    "NFL - Browns & Bengals": "CBS or Paramount+",
    "NFL - Ravens & Steelers": "CBS or Paramount+",
    "NFL - Jets & Bills": "CBS or Paramount+",
    "NFL - Jaguars & Titans": "CBS or Paramount+",
    "NFL - Dolphins & Chargers": "CBS or Paramount+",
    "NFL - Buccaneers & 49ers": "FOX",
    "NFL - Panthers & Seahawks": "FOX",
    "NFL - Chiefs & Broncos": "NBC or Peacock",
    "NFL - Patriots & Cardinals": "ESPN",
    "NFL - 49ers & Seahawks": "Amazon Prime",
    "EPL - Brighton & Hove Albion vs Nottingham Forest": "Optus Sport in Australia, USA Network & Universo in USA",
    "EPL - Crystal Palace vs Wolverhampton Wanderers": "Optus Sport in Australia, Peacock in USA",
    "EPL - Brentford vs Chelsea": "Optus Sport in Australia, USA Network & Universo in USA",
    "EPL - Newcastle vs Everton": "Optus Sport in Australia, Peacock in USA",
    "EPL - Liverpool vs West Ham": "Optus Sport in Australia, Peacock in USA",
    "EPL - Bournemouth vs Southampton": "Optus Sport in Australia, Peacock in USA",
    "EPL - Manchester United vs Tottenham": "Optus Sport in Australia, Peacock in USA",
    "EPL - Fulham vs Aston Villa": "Optus Sport in Australia, USA Network & Universo in USA",
    "EPL - Leicester City vs Leeds United": "Optus Sport in Australia, Peacock in USA",
    "EPL - Nottingham Forest vs Liverpool": "Optus Sport in Australia, USA Network & Universo in USA",
    "EPL - Everton vs Crystal Palace": "Optus Sport in Australia, USA Network & Universo in USA",
    "EPL - Manchester City vs Brighton & Hove Albion": "Optus Sport in Australia, Peacock in USA",
    "EPL - Chelsea vs Manchester United": "Optus Sport in Australia, NBC & Peacock & Universo in USA",
    "EPL - Wolverhampton Wanderers vs Leicester City": "Optus Sport in Australia, USA Network or Telemundo in USA",
    "EPL - Leeds United vs Fulham": "Optus Sport in Australia, CNBC in USA",
    "EPL - Southampton vs Arsenal": "Optus Sport in Australia, Peacock in USA",
    "EPL - Aston Villa vs Brentford": "Optus Sport in Australia, Peacock in USA",
    "EPL - Tottenham vs Newcastle": "Optus Sport in Australia, USA Network & Telemundo in USA",
    "EPL - West Ham vs Bournemouth": "Optus Sport in Australia, USA Network & Universo in USA",
    "A-League - Sydney FC vs Adelaide United": "10 Bold, 10 Play & Paramount+",
    "A-League - Central Coast Mariners vs Perth Glory": "10 Bold, 10 Play & Paramount+",
    "A-League - Western Sydney Wanderers vs Newcastle Jets": "Paramount+",
    "A-League - Brisbane Roar vs Melbourne Victory": "Paramount+",
    "A-League - Central Coast Mariners vs Western United": "Paramount+",
    "A-League - Macarthur FC vs Sydney FC": "10 Bold, 10 Play & Paramount+",
    "A-League - Adelaide United vs Perth Glory": "10 Bold, 10 Play & Paramount+",
    "A-League - Melbourne City vs Wellington Phoenix": "Paramount+",
    "A-League - Melbourne Victory vs Newcastle Jets": "Paramount+",
    "A-League - Melbourne City vs Perth Glory": "Paramount+",
    "A-League - Western Sydney Wanderers vs Central Coast Mariners": "10 Bold, 10 Play & Paramount+",
    "A-League - Wellington Phoenix vs Macarthur FC": "Paramount+",
    "A-League - Brisbane Roar vs Sydney FC": "10 Bold, 10 Play & Paramount+",
    "A-League - Western United vs Adelaide United": "Paramount+",
    "A-League - Adelaide United vs Melbourne Victory": "Paramount+",
    "A-League - Newcastle Jets vs Melbourne City": "Paramount+",
    "A-League - Sydney FC vs Western United": "10 Bold, 10 Play & Paramount+",
    "A-League - Wellington Phoenix vs Western United": "Paramount+",
    "A-League - Central Coast Mariners vs Macarthur FC": "Paramount+",
    "A-League - Brisbane Roar vs Adelaide United": "Paramount+",
    "A-League - Wellington Phoenix vs Western Sydney Wanderers": "Paramount+",
    "A-League - Perth Glory vs Western United": "Paramount+",
    "A-League - Sydney FC vs Melbourne City": "10 Bold, 10 Play & Paramount+",
    "A-League - Central Coast Mariners vs Newcastle Jets 1": "10 Bold, 10 Play & Paramount+",
    "A-League - Macarthur FC vs Melbourne Victory": "Paramount+",
    "A-League - Newcastle Jets vs Brisbane Roar": "Paramount+",
    "A-League - Wellington Phoenix vs Adelaide United": "Paramount+",
    "A-League - Central Coast Mariners vs Sydney FC": "Paramount+",
    "A-League - Melbourne City vs Melbourne Victory": "10 Bold, 10 Play & Paramount+",
    "A-League - Western United vs Western Sydney Wanderers": "Paramount+",
    "A-League - Macarthur FC vs Perth Glory": "Paramount+",
    "A-League - Central Coast Mariners vs Newcastle Jets 2": "Paramount+",







}



app.display()

#fix sport_network problem